//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.oorsprong.org/websamples.countryinfo", ClrNamespace="www.oorsprong.org.websamples.countryinfo")]

namespace www.oorsprong.org.websamples.countryinfo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tContinent : object
    {
        
        private string sCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCurrency : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndName", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndName : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndNameGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndNameGroupedByContinent : object
    {
        
        private www.oorsprong.org.websamples.countryinfo.tContinent ContinentField;
        
        private www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountryCodeAndNamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public www.oorsprong.org.websamples.countryinfo.tContinent Continent
        {
            get
            {
                return this.ContinentField;
            }
            set
            {
                this.ContinentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountryCodeAndNames
        {
            get
            {
                return this.CountryCodeAndNamesField;
            }
            set
            {
                this.CountryCodeAndNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryInfo : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        private string sCapitalCityField;
        
        private string sPhoneCodeField;
        
        private string sContinentCodeField;
        
        private string sCurrencyISOCodeField;
        
        private string sCountryFlagField;
        
        private www.oorsprong.org.websamples.countryinfo.tLanguage[] LanguagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string sCapitalCity
        {
            get
            {
                return this.sCapitalCityField;
            }
            set
            {
                this.sCapitalCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string sPhoneCode
        {
            get
            {
                return this.sPhoneCodeField;
            }
            set
            {
                this.sPhoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string sContinentCode
        {
            get
            {
                return this.sContinentCodeField;
            }
            set
            {
                this.sContinentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string sCurrencyISOCode
        {
            get
            {
                return this.sCurrencyISOCodeField;
            }
            set
            {
                this.sCurrencyISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public www.oorsprong.org.websamples.countryinfo.tLanguage[] Languages
        {
            get
            {
                return this.LanguagesField;
            }
            set
            {
                this.LanguagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLanguage", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tLanguage : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo", ConfigurationName="CountryInfoServiceSoapType")]
public interface CountryInfoServiceSoapType
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfContinentsByNameResponse> ListOfContinentsByNameAsync(ListOfContinentsByNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync(ListOfContinentsByCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync(ListOfCurrenciesByNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync(ListOfCurrenciesByCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CurrencyNameResponse> CurrencyNameAsync(CurrencyNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync(ListOfCountryNamesByCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync(ListOfCountryNamesByNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync(ListOfCountryNamesGroupedByContinentRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountryNameResponse> CountryNameAsync(CountryNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountryISOCodeResponse> CountryISOCodeAsync(CountryISOCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CapitalCityResponse> CapitalCityAsync(CapitalCityRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountryCurrencyResponse> CountryCurrencyAsync(CountryCurrencyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountryFlagResponse> CountryFlagAsync(CountryFlagRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(CountryIntPhoneCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<FullCountryInfoResponse> FullCountryInfoAsync(FullCountryInfoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync(FullCountryInfoAllCountriesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(CountriesUsingCurrencyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync(ListOfLanguagesByNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync(ListOfLanguagesByCodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<LanguageNameResponse> LanguageNameAsync(LanguageNameRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<LanguageISOCodeResponse> LanguageISOCodeAsync(LanguageISOCodeRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByNameRequestBody Body;
    
    public ListOfContinentsByNameRequest()
    {
    }
    
    public ListOfContinentsByNameRequest(ListOfContinentsByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfContinentsByNameRequestBody
{
    
    public ListOfContinentsByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByNameResponseBody Body;
    
    public ListOfContinentsByNameResponse()
    {
    }
    
    public ListOfContinentsByNameResponse(ListOfContinentsByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfContinentsByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByNameResult;
    
    public ListOfContinentsByNameResponseBody()
    {
    }
    
    public ListOfContinentsByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByNameResult)
    {
        this.ListOfContinentsByNameResult = ListOfContinentsByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByCodeRequestBody Body;
    
    public ListOfContinentsByCodeRequest()
    {
    }
    
    public ListOfContinentsByCodeRequest(ListOfContinentsByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfContinentsByCodeRequestBody
{
    
    public ListOfContinentsByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByCodeResponseBody Body;
    
    public ListOfContinentsByCodeResponse()
    {
    }
    
    public ListOfContinentsByCodeResponse(ListOfContinentsByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfContinentsByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByCodeResult;
    
    public ListOfContinentsByCodeResponseBody()
    {
    }
    
    public ListOfContinentsByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByCodeResult)
    {
        this.ListOfContinentsByCodeResult = ListOfContinentsByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByNameRequestBody Body;
    
    public ListOfCurrenciesByNameRequest()
    {
    }
    
    public ListOfCurrenciesByNameRequest(ListOfCurrenciesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCurrenciesByNameRequestBody
{
    
    public ListOfCurrenciesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByNameResponseBody Body;
    
    public ListOfCurrenciesByNameResponse()
    {
    }
    
    public ListOfCurrenciesByNameResponse(ListOfCurrenciesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCurrenciesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByNameResult;
    
    public ListOfCurrenciesByNameResponseBody()
    {
    }
    
    public ListOfCurrenciesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByNameResult)
    {
        this.ListOfCurrenciesByNameResult = ListOfCurrenciesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByCodeRequestBody Body;
    
    public ListOfCurrenciesByCodeRequest()
    {
    }
    
    public ListOfCurrenciesByCodeRequest(ListOfCurrenciesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCurrenciesByCodeRequestBody
{
    
    public ListOfCurrenciesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByCodeResponseBody Body;
    
    public ListOfCurrenciesByCodeResponse()
    {
    }
    
    public ListOfCurrenciesByCodeResponse(ListOfCurrenciesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCurrenciesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByCodeResult;
    
    public ListOfCurrenciesByCodeResponseBody()
    {
    }
    
    public ListOfCurrenciesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByCodeResult)
    {
        this.ListOfCurrenciesByCodeResult = ListOfCurrenciesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CurrencyNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CurrencyNameRequestBody Body;
    
    public CurrencyNameRequest()
    {
    }
    
    public CurrencyNameRequest(CurrencyNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CurrencyNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCurrencyISOCode;
    
    public CurrencyNameRequestBody()
    {
    }
    
    public CurrencyNameRequestBody(string sCurrencyISOCode)
    {
        this.sCurrencyISOCode = sCurrencyISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CurrencyNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CurrencyNameResponseBody Body;
    
    public CurrencyNameResponse()
    {
    }
    
    public CurrencyNameResponse(CurrencyNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CurrencyNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CurrencyNameResult;
    
    public CurrencyNameResponseBody()
    {
    }
    
    public CurrencyNameResponseBody(string CurrencyNameResult)
    {
        this.CurrencyNameResult = CurrencyNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByCodeRequestBody Body;
    
    public ListOfCountryNamesByCodeRequest()
    {
    }
    
    public ListOfCountryNamesByCodeRequest(ListOfCountryNamesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesByCodeRequestBody
{
    
    public ListOfCountryNamesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByCodeResponseBody Body;
    
    public ListOfCountryNamesByCodeResponse()
    {
    }
    
    public ListOfCountryNamesByCodeResponse(ListOfCountryNamesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByCodeResult;
    
    public ListOfCountryNamesByCodeResponseBody()
    {
    }
    
    public ListOfCountryNamesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByCodeResult)
    {
        this.ListOfCountryNamesByCodeResult = ListOfCountryNamesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByNameRequestBody Body;
    
    public ListOfCountryNamesByNameRequest()
    {
    }
    
    public ListOfCountryNamesByNameRequest(ListOfCountryNamesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesByNameRequestBody
{
    
    public ListOfCountryNamesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByNameResponseBody Body;
    
    public ListOfCountryNamesByNameResponse()
    {
    }
    
    public ListOfCountryNamesByNameResponse(ListOfCountryNamesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByNameResult;
    
    public ListOfCountryNamesByNameResponseBody()
    {
    }
    
    public ListOfCountryNamesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByNameResult)
    {
        this.ListOfCountryNamesByNameResult = ListOfCountryNamesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesGroupedByContinentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesGroupedByContinentRequestBody Body;
    
    public ListOfCountryNamesGroupedByContinentRequest()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentRequest(ListOfCountryNamesGroupedByContinentRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesGroupedByContinentRequestBody
{
    
    public ListOfCountryNamesGroupedByContinentRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesGroupedByContinentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinentResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesGroupedByContinentResponseBody Body;
    
    public ListOfCountryNamesGroupedByContinentResponse()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentResponse(ListOfCountryNamesGroupedByContinentResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesGroupedByContinentResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult;
    
    public ListOfCountryNamesGroupedByContinentResponseBody()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult)
    {
        this.ListOfCountryNamesGroupedByContinentResult = ListOfCountryNamesGroupedByContinentResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryNameRequestBody Body;
    
    public CountryNameRequest()
    {
    }
    
    public CountryNameRequest(CountryNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryNameRequestBody()
    {
    }
    
    public CountryNameRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryNameResponseBody Body;
    
    public CountryNameResponse()
    {
    }
    
    public CountryNameResponse(CountryNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryNameResult;
    
    public CountryNameResponseBody()
    {
    }
    
    public CountryNameResponseBody(string CountryNameResult)
    {
        this.CountryNameResult = CountryNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryISOCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryISOCodeRequestBody Body;
    
    public CountryISOCodeRequest()
    {
    }
    
    public CountryISOCodeRequest(CountryISOCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryISOCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryName;
    
    public CountryISOCodeRequestBody()
    {
    }
    
    public CountryISOCodeRequestBody(string sCountryName)
    {
        this.sCountryName = sCountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryISOCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryISOCodeResponseBody Body;
    
    public CountryISOCodeResponse()
    {
    }
    
    public CountryISOCodeResponse(CountryISOCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryISOCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryISOCodeResult;
    
    public CountryISOCodeResponseBody()
    {
    }
    
    public CountryISOCodeResponseBody(string CountryISOCodeResult)
    {
        this.CountryISOCodeResult = CountryISOCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CapitalCityRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCity", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CapitalCityRequestBody Body;
    
    public CapitalCityRequest()
    {
    }
    
    public CapitalCityRequest(CapitalCityRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CapitalCityRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CapitalCityRequestBody()
    {
    }
    
    public CapitalCityRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CapitalCityResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCityResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CapitalCityResponseBody Body;
    
    public CapitalCityResponse()
    {
    }
    
    public CapitalCityResponse(CapitalCityResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CapitalCityResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CapitalCityResult;
    
    public CapitalCityResponseBody()
    {
    }
    
    public CapitalCityResponseBody(string CapitalCityResult)
    {
        this.CapitalCityResult = CapitalCityResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryCurrencyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryCurrencyRequestBody Body;
    
    public CountryCurrencyRequest()
    {
    }
    
    public CountryCurrencyRequest(CountryCurrencyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryCurrencyRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryCurrencyRequestBody()
    {
    }
    
    public CountryCurrencyRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryCurrencyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryCurrencyResponseBody Body;
    
    public CountryCurrencyResponse()
    {
    }
    
    public CountryCurrencyResponse(CountryCurrencyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryCurrencyResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency CountryCurrencyResult;
    
    public CountryCurrencyResponseBody()
    {
    }
    
    public CountryCurrencyResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency CountryCurrencyResult)
    {
        this.CountryCurrencyResult = CountryCurrencyResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryFlagRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlag", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryFlagRequestBody Body;
    
    public CountryFlagRequest()
    {
    }
    
    public CountryFlagRequest(CountryFlagRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryFlagRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryFlagRequestBody()
    {
    }
    
    public CountryFlagRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryFlagResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlagResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryFlagResponseBody Body;
    
    public CountryFlagResponse()
    {
    }
    
    public CountryFlagResponse(CountryFlagResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryFlagResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryFlagResult;
    
    public CountryFlagResponseBody()
    {
    }
    
    public CountryFlagResponseBody(string CountryFlagResult)
    {
        this.CountryFlagResult = CountryFlagResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryIntPhoneCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryIntPhoneCodeRequestBody Body;
    
    public CountryIntPhoneCodeRequest()
    {
    }
    
    public CountryIntPhoneCodeRequest(CountryIntPhoneCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryIntPhoneCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryIntPhoneCodeRequestBody()
    {
    }
    
    public CountryIntPhoneCodeRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryIntPhoneCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryIntPhoneCodeResponseBody Body;
    
    public CountryIntPhoneCodeResponse()
    {
    }
    
    public CountryIntPhoneCodeResponse(CountryIntPhoneCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryIntPhoneCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryIntPhoneCodeResult;
    
    public CountryIntPhoneCodeResponseBody()
    {
    }
    
    public CountryIntPhoneCodeResponseBody(string CountryIntPhoneCodeResult)
    {
        this.CountryIntPhoneCodeResult = CountryIntPhoneCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoRequestBody Body;
    
    public FullCountryInfoRequest()
    {
    }
    
    public FullCountryInfoRequest(FullCountryInfoRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public FullCountryInfoRequestBody()
    {
    }
    
    public FullCountryInfoRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoResponseBody Body;
    
    public FullCountryInfoResponse()
    {
    }
    
    public FullCountryInfoResponse(FullCountryInfoResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryInfo FullCountryInfoResult;
    
    public FullCountryInfoResponseBody()
    {
    }
    
    public FullCountryInfoResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryInfo FullCountryInfoResult)
    {
        this.FullCountryInfoResult = FullCountryInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoAllCountriesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountries", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoAllCountriesRequestBody Body;
    
    public FullCountryInfoAllCountriesRequest()
    {
    }
    
    public FullCountryInfoAllCountriesRequest(FullCountryInfoAllCountriesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class FullCountryInfoAllCountriesRequestBody
{
    
    public FullCountryInfoAllCountriesRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoAllCountriesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountriesResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoAllCountriesResponseBody Body;
    
    public FullCountryInfoAllCountriesResponse()
    {
    }
    
    public FullCountryInfoAllCountriesResponse(FullCountryInfoAllCountriesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoAllCountriesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryInfo[] FullCountryInfoAllCountriesResult;
    
    public FullCountryInfoAllCountriesResponseBody()
    {
    }
    
    public FullCountryInfoAllCountriesResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryInfo[] FullCountryInfoAllCountriesResult)
    {
        this.FullCountryInfoAllCountriesResult = FullCountryInfoAllCountriesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountriesUsingCurrencyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountriesUsingCurrencyRequestBody Body;
    
    public CountriesUsingCurrencyRequest()
    {
    }
    
    public CountriesUsingCurrencyRequest(CountriesUsingCurrencyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountriesUsingCurrencyRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sISOCurrencyCode;
    
    public CountriesUsingCurrencyRequestBody()
    {
    }
    
    public CountriesUsingCurrencyRequestBody(string sISOCurrencyCode)
    {
        this.sISOCurrencyCode = sISOCurrencyCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountriesUsingCurrencyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountriesUsingCurrencyResponseBody Body;
    
    public CountriesUsingCurrencyResponse()
    {
    }
    
    public CountriesUsingCurrencyResponse(CountriesUsingCurrencyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountriesUsingCurrencyResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountriesUsingCurrencyResult;
    
    public CountriesUsingCurrencyResponseBody()
    {
    }
    
    public CountriesUsingCurrencyResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountriesUsingCurrencyResult)
    {
        this.CountriesUsingCurrencyResult = CountriesUsingCurrencyResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByNameRequestBody Body;
    
    public ListOfLanguagesByNameRequest()
    {
    }
    
    public ListOfLanguagesByNameRequest(ListOfLanguagesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfLanguagesByNameRequestBody
{
    
    public ListOfLanguagesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByNameResponseBody Body;
    
    public ListOfLanguagesByNameResponse()
    {
    }
    
    public ListOfLanguagesByNameResponse(ListOfLanguagesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfLanguagesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByNameResult;
    
    public ListOfLanguagesByNameResponseBody()
    {
    }
    
    public ListOfLanguagesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByNameResult)
    {
        this.ListOfLanguagesByNameResult = ListOfLanguagesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByCodeRequestBody Body;
    
    public ListOfLanguagesByCodeRequest()
    {
    }
    
    public ListOfLanguagesByCodeRequest(ListOfLanguagesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfLanguagesByCodeRequestBody
{
    
    public ListOfLanguagesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByCodeResponseBody Body;
    
    public ListOfLanguagesByCodeResponse()
    {
    }
    
    public ListOfLanguagesByCodeResponse(ListOfLanguagesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfLanguagesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByCodeResult;
    
    public ListOfLanguagesByCodeResponseBody()
    {
    }
    
    public ListOfLanguagesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByCodeResult)
    {
        this.ListOfLanguagesByCodeResult = ListOfLanguagesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageNameRequestBody Body;
    
    public LanguageNameRequest()
    {
    }
    
    public LanguageNameRequest(LanguageNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sISOCode;
    
    public LanguageNameRequestBody()
    {
    }
    
    public LanguageNameRequestBody(string sISOCode)
    {
        this.sISOCode = sISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageNameResponseBody Body;
    
    public LanguageNameResponse()
    {
    }
    
    public LanguageNameResponse(LanguageNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string LanguageNameResult;
    
    public LanguageNameResponseBody()
    {
    }
    
    public LanguageNameResponseBody(string LanguageNameResult)
    {
        this.LanguageNameResult = LanguageNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageISOCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageISOCodeRequestBody Body;
    
    public LanguageISOCodeRequest()
    {
    }
    
    public LanguageISOCodeRequest(LanguageISOCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageISOCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sLanguageName;
    
    public LanguageISOCodeRequestBody()
    {
    }
    
    public LanguageISOCodeRequestBody(string sLanguageName)
    {
        this.sLanguageName = sLanguageName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageISOCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageISOCodeResponseBody Body;
    
    public LanguageISOCodeResponse()
    {
    }
    
    public LanguageISOCodeResponse(LanguageISOCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageISOCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string LanguageISOCodeResult;
    
    public LanguageISOCodeResponseBody()
    {
    }
    
    public LanguageISOCodeResponseBody(string LanguageISOCodeResult)
    {
        this.LanguageISOCodeResult = LanguageISOCodeResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface CountryInfoServiceSoapTypeChannel : CountryInfoServiceSoapType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class CountryInfoServiceSoapTypeClient : System.ServiceModel.ClientBase<CountryInfoServiceSoapType>, CountryInfoServiceSoapType
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
            base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), CountryInfoServiceSoapTypeClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CountryInfoServiceSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfContinentsByNameResponse> CountryInfoServiceSoapType.ListOfContinentsByNameAsync(ListOfContinentsByNameRequest request)
    {
        return base.Channel.ListOfContinentsByNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfContinentsByNameResponse> ListOfContinentsByNameAsync()
    {
        ListOfContinentsByNameRequest inValue = new ListOfContinentsByNameRequest();
        inValue.Body = new ListOfContinentsByNameRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfContinentsByNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfContinentsByCodeResponse> CountryInfoServiceSoapType.ListOfContinentsByCodeAsync(ListOfContinentsByCodeRequest request)
    {
        return base.Channel.ListOfContinentsByCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync()
    {
        ListOfContinentsByCodeRequest inValue = new ListOfContinentsByCodeRequest();
        inValue.Body = new ListOfContinentsByCodeRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfContinentsByCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfCurrenciesByNameResponse> CountryInfoServiceSoapType.ListOfCurrenciesByNameAsync(ListOfCurrenciesByNameRequest request)
    {
        return base.Channel.ListOfCurrenciesByNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync()
    {
        ListOfCurrenciesByNameRequest inValue = new ListOfCurrenciesByNameRequest();
        inValue.Body = new ListOfCurrenciesByNameRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfCurrenciesByNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfCurrenciesByCodeResponse> CountryInfoServiceSoapType.ListOfCurrenciesByCodeAsync(ListOfCurrenciesByCodeRequest request)
    {
        return base.Channel.ListOfCurrenciesByCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync()
    {
        ListOfCurrenciesByCodeRequest inValue = new ListOfCurrenciesByCodeRequest();
        inValue.Body = new ListOfCurrenciesByCodeRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfCurrenciesByCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CurrencyNameResponse> CountryInfoServiceSoapType.CurrencyNameAsync(CurrencyNameRequest request)
    {
        return base.Channel.CurrencyNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<CurrencyNameResponse> CurrencyNameAsync(string sCurrencyISOCode)
    {
        CurrencyNameRequest inValue = new CurrencyNameRequest();
        inValue.Body = new CurrencyNameRequestBody();
        inValue.Body.sCurrencyISOCode = sCurrencyISOCode;
        return ((CountryInfoServiceSoapType)(this)).CurrencyNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfCountryNamesByCodeResponse> CountryInfoServiceSoapType.ListOfCountryNamesByCodeAsync(ListOfCountryNamesByCodeRequest request)
    {
        return base.Channel.ListOfCountryNamesByCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync()
    {
        ListOfCountryNamesByCodeRequest inValue = new ListOfCountryNamesByCodeRequest();
        inValue.Body = new ListOfCountryNamesByCodeRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesByCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfCountryNamesByNameResponse> CountryInfoServiceSoapType.ListOfCountryNamesByNameAsync(ListOfCountryNamesByNameRequest request)
    {
        return base.Channel.ListOfCountryNamesByNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync()
    {
        ListOfCountryNamesByNameRequest inValue = new ListOfCountryNamesByNameRequest();
        inValue.Body = new ListOfCountryNamesByNameRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesByNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfCountryNamesGroupedByContinentResponse> CountryInfoServiceSoapType.ListOfCountryNamesGroupedByContinentAsync(ListOfCountryNamesGroupedByContinentRequest request)
    {
        return base.Channel.ListOfCountryNamesGroupedByContinentAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync()
    {
        ListOfCountryNamesGroupedByContinentRequest inValue = new ListOfCountryNamesGroupedByContinentRequest();
        inValue.Body = new ListOfCountryNamesGroupedByContinentRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesGroupedByContinentAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountryNameResponse> CountryInfoServiceSoapType.CountryNameAsync(CountryNameRequest request)
    {
        return base.Channel.CountryNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountryNameResponse> CountryNameAsync(string sCountryISOCode)
    {
        CountryNameRequest inValue = new CountryNameRequest();
        inValue.Body = new CountryNameRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).CountryNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountryISOCodeResponse> CountryInfoServiceSoapType.CountryISOCodeAsync(CountryISOCodeRequest request)
    {
        return base.Channel.CountryISOCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountryISOCodeResponse> CountryISOCodeAsync(string sCountryName)
    {
        CountryISOCodeRequest inValue = new CountryISOCodeRequest();
        inValue.Body = new CountryISOCodeRequestBody();
        inValue.Body.sCountryName = sCountryName;
        return ((CountryInfoServiceSoapType)(this)).CountryISOCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CapitalCityResponse> CountryInfoServiceSoapType.CapitalCityAsync(CapitalCityRequest request)
    {
        return base.Channel.CapitalCityAsync(request);
    }
    
    public System.Threading.Tasks.Task<CapitalCityResponse> CapitalCityAsync(string sCountryISOCode)
    {
        CapitalCityRequest inValue = new CapitalCityRequest();
        inValue.Body = new CapitalCityRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).CapitalCityAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountryCurrencyResponse> CountryInfoServiceSoapType.CountryCurrencyAsync(CountryCurrencyRequest request)
    {
        return base.Channel.CountryCurrencyAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountryCurrencyResponse> CountryCurrencyAsync(string sCountryISOCode)
    {
        CountryCurrencyRequest inValue = new CountryCurrencyRequest();
        inValue.Body = new CountryCurrencyRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).CountryCurrencyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountryFlagResponse> CountryInfoServiceSoapType.CountryFlagAsync(CountryFlagRequest request)
    {
        return base.Channel.CountryFlagAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountryFlagResponse> CountryFlagAsync(string sCountryISOCode)
    {
        CountryFlagRequest inValue = new CountryFlagRequest();
        inValue.Body = new CountryFlagRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).CountryFlagAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountryIntPhoneCodeResponse> CountryInfoServiceSoapType.CountryIntPhoneCodeAsync(CountryIntPhoneCodeRequest request)
    {
        return base.Channel.CountryIntPhoneCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(string sCountryISOCode)
    {
        CountryIntPhoneCodeRequest inValue = new CountryIntPhoneCodeRequest();
        inValue.Body = new CountryIntPhoneCodeRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).CountryIntPhoneCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FullCountryInfoResponse> CountryInfoServiceSoapType.FullCountryInfoAsync(FullCountryInfoRequest request)
    {
        return base.Channel.FullCountryInfoAsync(request);
    }
    
    public System.Threading.Tasks.Task<FullCountryInfoResponse> FullCountryInfoAsync(string sCountryISOCode)
    {
        FullCountryInfoRequest inValue = new FullCountryInfoRequest();
        inValue.Body = new FullCountryInfoRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        return ((CountryInfoServiceSoapType)(this)).FullCountryInfoAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FullCountryInfoAllCountriesResponse> CountryInfoServiceSoapType.FullCountryInfoAllCountriesAsync(FullCountryInfoAllCountriesRequest request)
    {
        return base.Channel.FullCountryInfoAllCountriesAsync(request);
    }
    
    public System.Threading.Tasks.Task<FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync()
    {
        FullCountryInfoAllCountriesRequest inValue = new FullCountryInfoAllCountriesRequest();
        inValue.Body = new FullCountryInfoAllCountriesRequestBody();
        return ((CountryInfoServiceSoapType)(this)).FullCountryInfoAllCountriesAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CountriesUsingCurrencyResponse> CountryInfoServiceSoapType.CountriesUsingCurrencyAsync(CountriesUsingCurrencyRequest request)
    {
        return base.Channel.CountriesUsingCurrencyAsync(request);
    }
    
    public System.Threading.Tasks.Task<CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(string sISOCurrencyCode)
    {
        CountriesUsingCurrencyRequest inValue = new CountriesUsingCurrencyRequest();
        inValue.Body = new CountriesUsingCurrencyRequestBody();
        inValue.Body.sISOCurrencyCode = sISOCurrencyCode;
        return ((CountryInfoServiceSoapType)(this)).CountriesUsingCurrencyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfLanguagesByNameResponse> CountryInfoServiceSoapType.ListOfLanguagesByNameAsync(ListOfLanguagesByNameRequest request)
    {
        return base.Channel.ListOfLanguagesByNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync()
    {
        ListOfLanguagesByNameRequest inValue = new ListOfLanguagesByNameRequest();
        inValue.Body = new ListOfLanguagesByNameRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfLanguagesByNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ListOfLanguagesByCodeResponse> CountryInfoServiceSoapType.ListOfLanguagesByCodeAsync(ListOfLanguagesByCodeRequest request)
    {
        return base.Channel.ListOfLanguagesByCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync()
    {
        ListOfLanguagesByCodeRequest inValue = new ListOfLanguagesByCodeRequest();
        inValue.Body = new ListOfLanguagesByCodeRequestBody();
        return ((CountryInfoServiceSoapType)(this)).ListOfLanguagesByCodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<LanguageNameResponse> CountryInfoServiceSoapType.LanguageNameAsync(LanguageNameRequest request)
    {
        return base.Channel.LanguageNameAsync(request);
    }
    
    public System.Threading.Tasks.Task<LanguageNameResponse> LanguageNameAsync(string sISOCode)
    {
        LanguageNameRequest inValue = new LanguageNameRequest();
        inValue.Body = new LanguageNameRequestBody();
        inValue.Body.sISOCode = sISOCode;
        return ((CountryInfoServiceSoapType)(this)).LanguageNameAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<LanguageISOCodeResponse> CountryInfoServiceSoapType.LanguageISOCodeAsync(LanguageISOCodeRequest request)
    {
        return base.Channel.LanguageISOCodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<LanguageISOCodeResponse> LanguageISOCodeAsync(string sLanguageName)
    {
        LanguageISOCodeRequest inValue = new LanguageISOCodeRequest();
        inValue.Body = new LanguageISOCodeRequestBody();
        inValue.Body.sLanguageName = sLanguageName;
        return ((CountryInfoServiceSoapType)(this)).LanguageISOCodeAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
            httpBindingElement.AllowCookies = true;
            httpBindingElement.MaxBufferSize = int.MaxValue;
            httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
        {
            return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
        }
        if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
        {
            return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        CountryInfoServiceSoap,
        
        CountryInfoServiceSoap12,
    }
}
